# Generated by Django 5.1.5 on 2025-03-28 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Дата рождения', null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='desired_sleep_hours',
            field=models.PositiveSmallIntegerField(default=8, help_text='Норма часов сна в сутки', verbose_name='норма часов сна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], help_text='Пол', max_length=10, null=True, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Номер телефона', max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию профиля', null=True, upload_to='avatars/', verbose_name='фотография профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Обязательно. 4-20 символов. Только буквы, цифры и подчеркивания.', max_length=20, validators=[django.core.validators.RegexValidator(message='Имя пользователя может содержать только буквы, цифры и подчеркивания.', regex='^[a-zA-Z0-9_]+$')], verbose_name='имя пользователя'),
        ),
    ]
