# Generated by Django 5.1.5 on 2025-03-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_start', models.DateTimeField(help_text='Дата и время, когда пользователь лег спать.', verbose_name='Время отхода ко сну')),
                ('sleep_end', models.DateTimeField(help_text='Дата и время, когда пользователь проснулся.', verbose_name='Время пробуждения')),
                ('sleep_duration', models.DurationField(blank=True, help_text='Продолжительность сна, вычисляется автоматически.', null=True, verbose_name='Продолжительность сна')),
                ('wake_quality', models.PositiveSmallIntegerField(choices=[(1, 'Трудно проснулся'), (2, 'Нормальные ощущения'), (3, 'Легко проснулся')], default=2, help_text='Оценка того, насколько легко пользователь проснулся.', verbose_name='Оценка лёгкости пробуждения')),
                ('alertness', models.PositiveSmallIntegerField(choices=[(1, 'Очень уставший'), (2, 'Средний уровень бодрости'), (3, 'Полный энергии')], default=2, help_text='Оценка уровня бодрости пользователя в течение дня.', verbose_name='Уровень бодрости в течение дня')),
                ('note', models.TextField(blank=True, help_text='Дополнительные заметки пользователя о сне.', verbose_name='Заметка о сне')),
            ],
            options={
                'verbose_name': 'Запись о сне',
                'verbose_name_plural': 'Записи о сне',
                'db_table': 'app_sleep_records',
                'ordering': ['-sleep_start'],
            },
        ),
    ]
