# Generated by Django 5.0.11 on 2025-04-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_record_sleep_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-sleep_start'], 'verbose_name': 'Запись о сне'},
        ),
        migrations.AddField(
            model_name='record',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Автоматически сгенерированная рекомендация по улучшению сна.', null=True, verbose_name='Рекомендация по улучшению сна'),
        ),
        migrations.AlterField(
            model_name='record',
            name='wake_quality',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Трудно проснулся'), (2, 'Нормальные ощущения'), (3, 'Легко проснулся')], default=2, help_text='Оценка лёгкости пробуждения.', verbose_name='Лёгкость пробуждения'),
        ),
    ]
